import PDFDocument from "pdfkit";
import { SwissQRBill as PdfSwissQRBill } from "swissqrbill/pdf";
import { SwissQRBill as SvgSwissQRBill } from "swissqrbill/svg";
import { formatIBAN, formatReference } from "swissqrbill/utils";
import type { Data } from "swissqrbill/types";

import type { PaymentInput } from "../types/payment.js";
import { buildPaymentQuery } from "../utils/http.js";

export type BillLanguage = "DE" | "EN";

export interface RenderedBillLinks {
  apiJsonUrl: string;
  embedSvgUrl: string;
  pdfUrl: string;
  svgUrl: string;
  previewUrl: string;
}

export interface RenderedBillMetadata {
  generatedAt: string;
  input: PaymentInput;
  links: RenderedBillLinks;
  summary: Array<{ label: string; value: string }>;
}

const summaryLabels: Record<
  BillLanguage,
  {
    additionalAddress: string;
    address: string;
    amount: string;
    city: string;
    currency: string;
    payableBy: string;
    message: string;
    payee: string;
    personalNote: string;
    reference: string;
    summary: string;
    title: string;
    subtitle: string;
  }
> = {
  DE: {
    additionalAddress: "Zusätzliche Adresse",
    address: "Adresse",
    amount: "Betrag",
    payee: "Begünstigter",
    payableBy: "Zahlbar durch",
    city: "Ort",
    currency: "Währung",
    message: "Mitteilung",
    personalNote: "Persönliche Notiz",
    reference: "Referenz",
    summary: "Zusammenfassung",
    subtitle: "Generiert über die HTTP-API / HTML-Formular-Integration auf Basis von schoero/swissqrbill.",
    title: "Swiss QR Bill"
  },
  EN: {
    additionalAddress: "Additional address",
    address: "Address",
    amount: "Amount",
    city: "City",
    currency: "Currency",
    message: "Message",
    payee: "Payee",
    payableBy: "Payable by",
    personalNote: "Personal note",
    reference: "Reference",
    summary: "Summary",
    subtitle: "Generated from the HTTP API / HTML form wrapper around schoero/swissqrbill.",
    title: "Swiss QR Bill"
  }
};

function appendLanguage(params: URLSearchParams, language: BillLanguage): URLSearchParams {
  const next = new URLSearchParams(params);
  next.set("lang", language === "DE" ? "de" : "en");
  return next;
}

function toDebtor(input: PaymentInput): Data["debtor"] | undefined {
  if (
    input.debtorName === undefined ||
    input.debtorStreet === undefined ||
    input.debtorPostcode === undefined ||
    input.debtorCity === undefined
  ) {
    return undefined;
  }

  return {
    address: input.debtorStreet,
    buildingNumber: input.debtorNumber,
    city: input.debtorCity,
    country: input.debtorCountry ?? "CH",
    name: input.debtorName,
    zip: input.debtorPostcode
  };
}

function toSwissQrData(input: PaymentInput): Data {
  return {
    amount: input.amount,
    creditor: {
      account: input.iban,
      address: input.street,
      buildingNumber: input.number,
      city: input.city,
      country: input.country,
      name: input.name,
      zip: input.postcode
    },
    currency: input.currency,
    debtor: toDebtor(input),
    message: input.message,
    reference: input.reference
  };
}

function toPdfBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer | string) => {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    });

    doc.once("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.once("error", reject);
  });
}

export function renderSvg(input: PaymentInput, language: BillLanguage = "EN"): string {
  const qrBill = new SvgSwissQRBill(toSwissQrData(input), {
    language,
    outlines: true,
    scissors: true
  });

  return qrBill.toString();
}

export async function renderPdf(input: PaymentInput, language: BillLanguage = "EN"): Promise<Buffer> {
  const labels = summaryLabels[language];
  const doc = new PDFDocument({
    compress: true,
    margin: 42,
    size: "A4"
  });

  const bufferPromise = toPdfBuffer(doc);

  doc.info.Title = `Swiss QR Bill - ${input.name}`;
  doc.info.Subject = "Swiss QR Bill generated by swissqrbill-microservice";
  doc.info.Author = "swissqrbill-microservice";

  doc.font("Helvetica-Bold").fontSize(22).fillColor("#0f172a").text(labels.title);
  doc.moveDown(0.3);
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor("#475569")
    .text(labels.subtitle);

  doc.moveDown(1.2);
  doc.font("Helvetica-Bold").fontSize(11).fillColor("#0f172a").text(labels.summary);
  doc.moveDown(0.2);

  const summary = buildSummary(input, language);
  for (const row of summary) {
    doc
      .font("Helvetica-Bold")
      .fontSize(9)
      .fillColor("#0f172a")
      .text(`${row.label}: `, { continued: true })
      .font("Helvetica")
      .fillColor("#334155")
      .text(row.value);
  }

  const qrBill = new PdfSwissQRBill(toSwissQrData(input), {
    language,
    outlines: true,
    scissors: true
  });

  qrBill.attachTo(doc);
  doc.end();

  return bufferPromise;
}

export function buildLinks(input: PaymentInput, language: BillLanguage = "EN"): RenderedBillLinks {
  const params = buildPaymentQuery(input);
  const localizedParams = appendLanguage(params, language);
  const query = localizedParams.toString();

  return {
    apiJsonUrl: `/api/qr?${query}&format=json`,
    embedSvgUrl: `/api/qr?${query}&format=svg`,
    pdfUrl: `/api/qr?${query}&format=pdf&download=1`,
    previewUrl: `/?${query}`,
    svgUrl: `/api/qr?${query}&format=svg&download=1`
  };
}

export function buildSummary(input: PaymentInput, language: BillLanguage = "EN"): Array<{ label: string; value: string }> {
  const labels = summaryLabels[language];
  const rows: Array<{ label: string; value: string }> = [
    { label: labels.payee, value: input.name },
    {
      label: labels.address,
      value: [input.street, input.number].filter(Boolean).join(" ")
    },
    {
      label: labels.city,
      value: [input.postcode, input.city].filter(Boolean).join(" ")
    },
    { label: "IBAN", value: formatIBAN(input.iban) },
    { label: labels.currency, value: input.currency }
  ];

  if (input.amount !== undefined) {
    rows.push({ label: labels.amount, value: input.amount.toFixed(2) });
  }

  if (input.reference !== undefined) {
    rows.push({ label: labels.reference, value: formatReference(input.reference) });
  }

  if (input.message !== undefined) {
    rows.push({ label: labels.message, value: input.message });
  }

  if (input.debtorName !== undefined && input.debtorStreet !== undefined && input.debtorPostcode !== undefined && input.debtorCity !== undefined) {
    rows.push({
      label: labels.payableBy,
      value: [
        input.debtorName,
        [input.debtorStreet, input.debtorNumber].filter(Boolean).join(" "),
        [input.debtorPostcode, input.debtorCity].filter(Boolean).join(" "),
        input.debtorCountry ?? "CH"
      ]
        .filter(Boolean)
        .join(", ")
    });
  }

  if (input.address !== undefined) {
    rows.push({ label: labels.additionalAddress, value: input.address });
  }

  if (input.personalNote !== undefined) {
    rows.push({ label: labels.personalNote, value: input.personalNote });
  }

  return rows;
}

export function buildMetadata(input: PaymentInput, language: BillLanguage = "EN"): RenderedBillMetadata {
  return {
    generatedAt: new Date().toISOString(),
    input,
    links: buildLinks(input, language),
    summary: buildSummary(input, language)
  };
}
