import PDFDocument from "pdfkit";
import { SwissQRBill as PdfSwissQRBill } from "swissqrbill/pdf";
import { SwissQRBill as SvgSwissQRBill } from "swissqrbill/svg";
import { formatIBAN, formatReference } from "swissqrbill/utils";
import type { Data } from "swissqrbill/types";

import type { PaymentInput } from "../types/payment.js";
import { buildPaymentQuery } from "../utils/http.js";

export interface RenderedBillLinks {
  apiJsonUrl: string;
  pdfUrl: string;
  svgUrl: string;
  previewUrl: string;
}

export interface RenderedBillMetadata {
  bic?: string;
  generatedAt: string;
  input: PaymentInput;
  links: RenderedBillLinks;
  summary: Array<{ label: string; value: string }>;
}

function toSwissQrData(input: PaymentInput): Data {
  return {
    amount: input.amount,
    creditor: {
      account: input.iban,
      address: input.street,
      buildingNumber: input.number,
      city: input.city,
      country: input.country,
      name: input.name,
      zip: input.postcode
    },
    currency: input.currency,
    message: input.message,
    reference: input.reference
  };
}

function toPdfBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer | string) => {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    });

    doc.once("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.once("error", reject);
  });
}

export function renderSvg(input: PaymentInput): string {
  const qrBill = new SvgSwissQRBill(toSwissQrData(input), {
    language: "EN",
    outlines: true,
    scissors: true
  });

  return qrBill.toString();
}

export async function renderPdf(input: PaymentInput): Promise<Buffer> {
  const doc = new PDFDocument({
    compress: true,
    margin: 42,
    size: "A4"
  });

  const bufferPromise = toPdfBuffer(doc);

  doc.info.Title = `Swiss QR Bill - ${input.name}`;
  doc.info.Subject = "Swiss QR Bill generated by swissqrbill-microservice";
  doc.info.Author = "swissqrbill-microservice";

  doc.font("Helvetica-Bold").fontSize(22).fillColor("#0f172a").text("Swiss QR Bill");
  doc.moveDown(0.3);
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor("#475569")
    .text("Generated from the HTTP API / HTML form wrapper around schoero/swissqrbill.");

  doc.moveDown(1.2);
  doc.font("Helvetica-Bold").fontSize(11).fillColor("#0f172a").text("Summary");
  doc.moveDown(0.2);

  const summary = buildSummary(input);
  for (const row of summary) {
    doc
      .font("Helvetica-Bold")
      .fontSize(9)
      .fillColor("#0f172a")
      .text(`${row.label}: `, { continued: true })
      .font("Helvetica")
      .fillColor("#334155")
      .text(row.value);
  }

  const qrBill = new PdfSwissQRBill(toSwissQrData(input), {
    language: "EN",
    outlines: true,
    scissors: true
  });

  qrBill.attachTo(doc);
  doc.end();

  return bufferPromise;
}

export function buildLinks(input: PaymentInput): RenderedBillLinks {
  const params = buildPaymentQuery(input);
  const query = params.toString();

  return {
    apiJsonUrl: `/api/qr?${query}&format=json`,
    pdfUrl: `/api/qr?${query}&format=pdf&download=1`,
    previewUrl: `/?${query}`,
    svgUrl: `/api/qr?${query}&format=svg&download=1`
  };
}

export function buildSummary(input: PaymentInput): Array<{ label: string; value: string }> {
  const rows: Array<{ label: string; value: string }> = [
    { label: "Payee", value: input.name },
    {
      label: "Address",
      value: [input.street, input.number].filter(Boolean).join(" ")
    },
    {
      label: "City",
      value: [input.postcode, input.city].filter(Boolean).join(" ")
    },
    { label: "IBAN", value: formatIBAN(input.iban) },
    { label: "Currency", value: input.currency }
  ];

  if (input.amount !== undefined) {
    rows.push({ label: "Amount", value: input.amount.toFixed(2) });
  }

  if (input.reference !== undefined) {
    rows.push({ label: "Reference", value: formatReference(input.reference) });
  }

  if (input.bic !== undefined) {
    rows.push({ label: "BIC", value: input.bic });
  }

  if (input.message !== undefined) {
    rows.push({ label: "Message", value: input.message });
  }

  if (input.address !== undefined) {
    rows.push({ label: "Additional address", value: input.address });
  }

  if (input.personalNote !== undefined) {
    rows.push({ label: "Personal note", value: input.personalNote });
  }

  return rows;
}

export function buildMetadata(input: PaymentInput): RenderedBillMetadata {
  return {
    bic: input.bic,
    generatedAt: new Date().toISOString(),
    input,
    links: buildLinks(input),
    summary: buildSummary(input)
  };
}
